### ISSUE TITLE
Invalid config for 'notify' at configuration.yaml, line 212: required key 'platform' not provided

### ISSUE THREAD

**Issue by kimsvane** [qrioniclabs/homeassistant-mysql_command#10]
Hi 

Im getting

Invalid config for 'notify' at configuration.yaml, line 212: required key 'platform' not provided

I have this in my config file:

#### Write to db
notify:
  - name: mysql_command_sdcc_db
    platform: mysql_command
    host: 192.168.1.169
    username:un
    password: pw
    db: sdcc

  - service: notify.mysql_command_sdcc_db
    data_template:
      message: >
        INSERT INTO `table` (datetime, column1, column2) VALUES ('{{ now().timestamp() | timestamp_custom('%Y-%m-%d %H:%M:%S') }}', 'value1', 'value2');

I might be doing it wrong, please assist

**Comment by clau-bucur** [comment]
It works for me like this:
```
notify:
  - name: mysql_command
    platform: mysql_command
    host: xxxx`
    username: xxx
    password: xxx
    db: homeassistant
```
